### ISSUE TITLE
Impossible to add git on Xcode projects

### ISSUE THREAD

**Issue by altarofwisdom-perso** [bluecataudio/plugnscript#25]
As Xcode is unable to add git to an already existing project, and due the fact that no matter what I try I haven't been able to figure out how to create an empty XCode project that generates what PNS is expecting, could you create a sample project that already has git implemented, or explain in details how such a project should be created from scratch in Xcode ?

Thanks,

**Comment by altarofwisdom** [comment]
Moreover, generating a mh_bundle currently ends up in PNS triggering an error at lorad:
Loading script file: /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST
Error: Unexpected token '<unrecognized token>' in /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST(1:1)
Error: Unexpected token '<unrecognized token>' in /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST(1:139)
Error: Unexpected token '<unrecognized token>' in /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST(1:155)
Error: Unexpected token '<unrecognized token>' in /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST(7:1)
Error: Unexpected token '<unrecognized token>' in /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST(9:1)
Error: Unexpected token '<unrecognized token>' in /Users/yoto/Music/PNS/Tritium-VST/DerivedData/Tritium-VST/Build/Products/Debug/Tritium-VST.___VARIABLE_bundleExtension___/Contents/MacOS/Tritium-VST(10:1)
Error: failed to initialize script

Generating a dynamic library on the other hand seem to work (I haven't tried exporting it but at loads in PNS)

**Comment by bluecataudio** [comment]
Adding git to sample projects is not an option, but have you tried to use the xcconfig files to create your projects, as explained in the README.TXT?

https://github.com/bluecataudio/plugnscript/tree/master/Built-in/NativeSource/build/XCode/Xcconfig

This avoids having to setup all options everytime manually. You can read more about xcconfig files here: https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project

**Comment by altarofwisdom** [comment]
That's what I'm trying to do, however none of the project types I've tried when creating the project generates the right file type (I have tried library and bundle in the project creation menu, to no avail), so I fail to even start adding anything as Xcode won't generate anything that PNS will be able to open (see my message above):
<img width="683" alt="image" src="https://github.com/bluecataudio/plugnscript/assets/122935531/8086bd64-d462-4c0e-9a97-267b8a89e2d0">

**Comment by bluecataudio** [comment]
Project type should be dynamic library (mh_dylib). Once the project is created, you can reference the xcconfig file AND also remove all the overriden values in the build settings so that the proper settings from the xcconfig file applies.

**Comment by altarofwisdom** [comment]
Seems to work now, I had to:
- remove overriden values from build settings (you actually can press delete on a line to reset to default !)
- Add these to common.xcconfig to have build outputting where I have placed my kuiml and data elements:
      DEPLOYMENT_LOCATION = YES
      INSTALL_PATH = .
      DSTROOT = $(SRCROOT)/Output/
Thanks !

**Comment by bluecataudio** [comment]
Great! Thanks for the heads up!
