### ISSUE TITLE
Sampler?

### ISSUE THREAD

**Issue by daslicht** [bluecataudio/plugnscript#9]
Hi,
is it possible to create a Sampler with Pluginscript?

**Comment by bluecataudio** [comment]
Yes, it is possible. Do you want to write a sampler that records samples or a sample player?
With angelscript you have a few limitations due to performace and API access (but file open and save are available), but in C++ you can actually do anything.

**Comment by daslicht** [comment]
It would be lovely to be able to recond and playback samples.

How is teh GUI coded ? Are there ready widgets ? 
What about drag and drop? eg vst-xml ?

**Comment by daslicht** [comment]
For the beginning I would be happy to create a simple Rompler

**Comment by bluecataudio** [comment]
You may want to have a look at the file reader sample and see how to load and play a wavefile. For a real sampler you will need to perform additional re-sampling when loading the files.

**Comment by bluecataudio** [comment]
The GUI is written with the KUIML language: http://www.bluecataudio.com//Vault/Skins/KUIML/
